// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYuY9f3piNMUir_RW9D3OfjCbAhmAWOXQ',
    appId: '1:75080845143:web:c844a3b0d2c78058742012',
    messagingSenderId: '75080845143',
    projectId: 'cmsc23-jaungos',
    authDomain: 'cmsc23-jaungos.firebaseapp.com',
    storageBucket: 'cmsc23-jaungos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1TWuk-S2aEUvAqbd2ypjAP2EPqYPSs1U',
    appId: '1:75080845143:android:ffab88d195c8c268742012',
    messagingSenderId: '75080845143',
    projectId: 'cmsc23-jaungos',
    storageBucket: 'cmsc23-jaungos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKteDpep7IStLEUnDRiUyo55kYTnYPwuM',
    appId: '1:75080845143:ios:08c0ac88de2ffd40742012',
    messagingSenderId: '75080845143',
    projectId: 'cmsc23-jaungos',
    storageBucket: 'cmsc23-jaungos.appspot.com',
    iosClientId: '75080845143-hg9eqb7oe7mm7i3jvmr3tmkberlpvk7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKteDpep7IStLEUnDRiUyo55kYTnYPwuM',
    appId: '1:75080845143:ios:08c0ac88de2ffd40742012',
    messagingSenderId: '75080845143',
    projectId: 'cmsc23-jaungos',
    storageBucket: 'cmsc23-jaungos.appspot.com',
    iosClientId: '75080845143-hg9eqb7oe7mm7i3jvmr3tmkberlpvk7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
